server:
  port: 9200

spring:
  application:
    name: api-order-submit
  redis:
    host: 192.168.153.130
    port: 6379
    database: 0
  rabbitmq:
    host: 192.168.153.130
    port: 5672
    virtual-host: host1
    username: rainlu
    password: rainlu996

    # 在SpringBoot中保证：消息可靠性（⽣产者发送消息 —— 消息队列存储消息）
    publisher-confirm-type: simple     # 开启消息确认模式
    publisher-returns: true            # 使⽤return监听机制

eureka:
  client:
    service-url:
      defaultZone: http://rainlu:123456@localhost:8761/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ConnectTimeout: 1000
  MaxAutoRetries: 2
  ReadTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000